export var estados=[
    [1,2,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null],
    [null,null,3,4,5,6,7,8,null,null,null,null,null,null,null,null,null],
    [null,null,null,null,null,null,null,null,9,10,11,12,13,14,null,null,null],
    [null,null,null,null,null,null,null,null,null,null,null,null,null,null,15,15,null],
    [null,null,null,null,null,null,null,null,null,null,null,null,null,null,16,17,null],
    [null,null,null,null,null,null,null,null,null,null,null,null,null,null,17,19,null],
    [null,null,null,null,null,null,null,null,null,null,null,null,null,null,19,20,null],
    [null,null,null,null,null,null,null,null,null,null,null,null,null,null,20,22,null],
    [null,null,null,null,null,null,null,null,null,null,null,null,null,null,22,24,null],
    [null,null,null,null,null,null,null,null,null,null,null,null,null,null,16,8,null],
    [null,null,null,null,null,null,null,null,null,null,null,null,null,null,16,8,null],
    [null,null,null,null,null,null,null,null,null,null,null,null,null,null,7,26,null],
    [null,null,null,null,null,null,null,null,null,null,null,null,null,null,18,8,null],
    [null,null,null,null,null,null,null,null,null,null,null,null,null,null,19,25,null],
    [null,null,null,null,null,null,null,null,null,null,null,null,null,null,5,25,null],
    [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,333],
    [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,333],
    [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,333],
    [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,333],
    [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,333],
    [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,333],
    [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,333],
    [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,333],
    [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,333],
    [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,333],
    [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,333]
  ];

  export var eQuestion=[
    "COMO TE SIENTES? BIEN O MAL",
    "COMO ESTAS? Calmado Sereno Contento Feliz Alegre Alerta",
    "COMO ESTAS? Tenso Nervioso Estresado Molesto Triste Deprimido",
    "QUERES CALMARLO? Si o No",
    "QUERES CALMARLO? Si o No",	
    "QUERES CALMARLO? Si o No",	
    "QUERES CALMARLO? Si o No",	
    "QUERES CALMARLO? Si o No",	
    "QUERES CALMARLO? Si o No",					
    "QUERES CALMARLO? Si o No",	
    "QUERES CALMARLO? Si o No",	
    "QUERES CALMARLO? Si o No",	
    "QUERES CALMARLO? Si o No",	
    "QUERES CALMARLO? Si o No",	
    "QUERES CALMARLO? Si o No",
    "Disfruta Tu Cancion",
    "Disfruta Tu Cancion",
    "Disfruta Tu Cancion",
    "Disfruta Tu Cancion",
    "Disfruta Tu Cancion",
    "Disfruta Tu Cancion",
    "Disfruta Tu Cancion",
    "Disfruta Tu Cancion",
    "Disfruta Tu Cancion",
    "Disfruta Tu Cancion",
    "Disfruta Tu Cancion"
  ]